### ISSUE TITLE
Changed the Persistance to InMemory for testing which throwed below error, can this be fixed

### ISSUE THREAD

**Issue by ksathiyaprakash** [tekmaven/NServiceBus.Persistence.MongoDb#4]
2015-01-29 16:30:14.418 ERROR NServiceBus.GenericHost Exception when starting endpoint.
System.InvalidOperationException: Messages containing databus properties found, please configure a databus using the ConfigureFileShareDataBus.FileShareDataBus extension method for ConfigurationBuilder.
   at NServiceBus.Features.DataBusFileBased.Setup(FeatureConfigurationContext context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\DataBus\DataBusFileBased.cs:line 30
   at NServiceBus.Features.Feature.SetupFeature(FeatureConfigurationContext config) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Features\Feature.cs:line 203
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Features\FeatureActivator.cs:line 233
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Features\FeatureActivator.cs:line 118
   at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Bus.cs:line 21
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 121
   at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 58

**Comment by tekmaven** [comment]
Thanks for reporting this issue.  I will investigate this and report back when I have an update.

**Comment by SimonCropp** [comment]
this is not a problem in this repo. if u have databus properties on messages you need to have a databus configured.
