### ISSUE TITLE
Incompatible with Mongo Driver 2.x

### ISSUE THREAD

**Issue by tonyeung** [tekmaven/NServiceBus.Persistence.MongoDb#5]
Not compatible with Mongo Driver 2.x.

We use some of the 2.x capabilities for aggregation, so there's a version missmatch when it tries to find the correct driver version

**Comment by tonyeung** [comment]
I tried updating the driver (no build issues), including the project into my solution, delete the nuget reference, add the project reference, but then I get this error:

```
Method 'GetService' in type 'System.ComponentModel.ISite__impl' 
from assembly 'NServiceBusMessageProxies, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' 
does not have an implementation.
```

    at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
      at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
      at System.Reflection.Emit.TypeBuilder.CreateType()
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.ConcreteProxyCreator.CreateTypeFrom(Type type) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\ConcreteProxyCreator.cs:line 96
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.GenerateImplementationFor(Type interfaceType) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 120
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 87
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 103
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 103
      at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.Initialize(IEnumerable`1 types) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 38
      at NServiceBus.Serializers.XML.Config.MessageTypesInitializer.Run(Configure config) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Serializers\XML\Config\MessageTypesInitializer.cs:line 26
      at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 123
      at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 21
      at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 121
      at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 70
      at NServiceBus.Hosting.Windows.WindowsHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\WindowsHost.cs:line 30
      at NServiceBus.Hosting.Windows.Program.<>c__DisplayClasse.<Main>b__6(WindowsHost service) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\Program.cs:line 80
      at Topshelf.Internal.ControllerDelegates`1.StartActionObject(Object obj) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\ControllerDelegates.cs:line 18
      at Topshelf.Internal.IsolatedServiceControllerWrapper`1.<>c__DisplayClass2.<set_StartAction>b__1(TService service) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\IsolatedServiceControllerWrapper.cs:line 65
      at Topshelf.Internal.ServiceController`1.<.cctor>b__1(ServiceController`1 sc) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\ServiceController.cs:line 35
      at Magnum.StateMachine.LambdaAction`1.Execute(T instance, Event event, Object parameter) in :line 0
      at Magnum.StateMachine.EventActionList`1.Execute(T stateMachine, Event event, Object parameter) in :line 0

**Comment by tekmaven** [comment]
Please check out the `feature-mongocsharp2.0` branch.  We have begun rewriting all of the mongodb calls to use the new API.  https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/tree/feature-mongocsharp2.0

**Comment by tonyeung** [comment]
Nice, what's left on it?

**Comment by tonyeung** [comment]
FWIW, when I try to include the feature branch into my project I get the same error as the OP

**Comment by tekmaven** [comment]
The stack trace you sent me looks like it is a problem outside of our codebase.  Does it work properly if you set persistence to InMemory?

If it does, could you maybe upload a minimal sample demonstrating the behavior to github and I can take a look/debug it.

**Comment by tonyeung** [comment]
Thanks, I'll test it and see. If its still a problem I'll create a repro and link it tomorrow.

**Comment by tonyeung** [comment]
Tested it, still "doesn't work". Not quite the same problem, but I think its related. 
Repro here https://github.com/tonyeung/ISite__impl.GetService.not_impl

The second commit is a working inmemory pub sub sample. 
The third commit is updated to use the feature branch project and then it dies.

**Comment by tekmaven** [comment]
Thanks!  I will check this out and try to figure it out!

**Comment by thomaswdean** [comment]
I work with Ton and we were wondering if there is a eta on this. Thank you.

**Comment by tekmaven** [comment]
We've released an updated nuget package which targets the latest MongoDB Client Driver.
